import type { Metadata } from "next"

import "./globals.css"
import Navbar from "@/components/Navbar"
import Providers from "./providers"

export const metadata: Metadata = {
  title: "Awesome App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html data-theme="cupcake">
      <body>
        <Navbar />
        <main className="px-8 py-20 max-w-6xl mx-auto">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  )
}
